### ISSUE TITLE
SQLSTATE[HY000]: General error when trying to post

### ISSUE THREAD

**Issue by sament** [arrilot/laravel-api-generator#3]
Thanks for this useful Laravel package.

I am using Laravel 5.3

After running the command **php artisan make:api InsurancePlan** it generates the files.
When I do a **GET api/v1/InsurancePlan** it returns values
However when I do a **POST api/v1/InsurancePlan** 
_{
"data": [
{
	"name": "plan 6",
	"description" : "desc",
	"status":1,
	"description": "what"
	}
	]
}_
 it returns error as follows:
_{
    "error": {
        "message": "SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `insurance_plan` (`updated_at`, `created_at`) values (2017-08-11 04:50:07, 2017-08-11 04:50:07))",
        "code": "HY000",
        "status_code": 500
    }
}_

Kindly note that my model classes are Eloquent models and contains fields in  $fillable.

I googled and saw setting strict=false in config/database.php but that allows inserting null values.

I am hoping it stores values as pass through the data json.

What am I doing wrong?

************************************
THE FILES
**InsurancePlanTransformer.php**

namespace App\Api\Transformers;

use App\Models\InsurancePlan;
use League\Fractal\TransformerAbstract;

class InsurancePlanTransformer extends TransformerAbstract
{
    /**
     * Turn this item object into a generic array.
     *
     * @param $item
     * @return array
     */
    public function transform(InsurancePlan $item)
    {
        return [
            'id'         => (int)$item->id,
			'name' 		 => (string)$item->name,
			'description' 		 => (string)$item->description,
            'created_at' => (string)$item->created_at,
            'updated_at' => (string)$item->updated_at,
        ];
    }
}

**InsurancePlanl.php**

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class InsurancePlan
 * 
 * @property int $id
 * @property string $name
 * @property string $description
 * @property bool $status
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * 
 * @property \Illuminate\Database\Eloquent\Collection $insurance_provider_benefits
 * @property \Illuminate\Database\Eloquent\Collection $insurance_provider_offerings
 *
 * @package App\Models
 */
class InsurancePlan extends Eloquent
{
	protected $table = 'insurance_plan';

	protected $casts = [
		'status' => 'bool'
	];

	protected $fillable = [
		'name',
		'description',
		'status'
	];
}

Thanks for your help in advance :)

**Comment by arrilot** [comment]
Sorry I do not have a setup to help you debugging this atm.
I recommend you to go to this file inside your vendor directory https://github.com/arrilot/laravel-api-generator/blob/master/src/Skeleton/BaseController.php and debug it manually.
Should be fairly simple, good luck
